"""Add Auth schema

Revision ID: 42430ef650e8
Revises: b8188dd8bf77
Create Date: 2026-04-07 14:17:00.600873
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42430ef650e8'
down_revision: Union[str, None] = 'b8188dd8bf77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('headline', sa.String(length=500), nullable=True))
    op.create_unique_constraint('uq_member_user_org', 'organization_members', ['user_id', 'organization_id'])
    op.add_column('organizations', sa.Column('industry', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('contact_email', sa.String(length=320), nullable=True))
    op.add_column('organizations', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('users', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_active')
    op.drop_column('organizations', 'is_active')
    op.drop_column('organizations', 'contact_email')
    op.drop_column('organizations', 'industry')
    op.drop_constraint('uq_member_user_org', 'organization_members', type_='unique')
    op.drop_column('candidates', 'headline')
    # ### end Alembic commands ###
