"""add requirements and experience_level to jobs

Revision ID: 80a2c3cb4e2f
Revises: c01234567890
Create Date: 2026-04-10 09:02:48.981847
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a2c3cb4e2f'
down_revision: Union[str, None] = 'c01234567890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('experience_level', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('requirements', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'requirements')
    op.drop_column('jobs', 'experience_level')
    # ### end Alembic commands ###
